### ISSUE TITLE
How to get the auth key?

### ISSUE THREAD

**Issue by Jelosus2** [jvergerolle/Genshin-Impact-Wish-history-API#1]
Hi, i was trying to fetch my wish history by doing a request but says to me invalid auth key and i wonder how i can get it, thanks in advantage!

**Comment by jvergerolle** [comment]
Hi, yes since 2.3 version only authkeys issued to request the wish history are allowed, it's mentioned at the end of the README.
> Mihoyo has changed the authentication method to request the API. The authkey to get wish data must be from the webview_gatcha app (wish history page) in order to get the wish history.

In order to get a valid authkey you have to look at the requests made when accessing the wish history page with a web debugging proxy.

Otherwise, after accessing the history in game on Windows, the wish history page URL is also written in `%userprofile%\AppData\LocalLow\miHoYo\Genshin Impact\output_log.txt` (for the global game client) or `%userprofile%\AppData\LocalLow\miHoYo\原神\\output_log.txt` on the Chinese client.

There is some powershell script like [this one](https://github.com/genshin-wishes/genshin-wishes-getlink) that can help you find the URL. I'm also working on a no-script / no installation version here is a [prototype ](https://codepen.io/jvergerolle/full/GRMerxY)

**Comment by Jelosus2** [comment]
Ok, thanks, in mobile you can get the link turning off the wifi and selecting all the error, but idk when the authkey ends, this is a link: web https://webstatic-sea.mihoyo.com/hk4e/event/e20190909gacha/index.html?authkey_ver=1&sign_type=2&auth_appid=webview_gacha&init_type=301&gacha_id=65d8a446ed5b40a0932cf0a66ffa2c13392f72&timestamp=1644968924&lang=es&device_type=mobile&ext=%7b%22loc%22%3a%7b%22x%22%3a2281.491455078125%2c%22y%22%3a221.10440063476563%2c%22z%22%3a-867.7012939453125%7d%2c%22platform%22%3a%22Android%22%7d&game_version=OSRELAndroid2.5.0_R5923384_S5909260_D5939455&plat_type=android&region=os_euro&authkey=bt5regz5uDhGaQ07Kpgkiyug8JXJ5x0fnsBaNsAyseo6HBEz3v5PUwDkr0M1ssTnrFnszfQe6Su8w7fALN2FDmXzRTrbDVwyZAzU0SwbBLl5z7mh%2ftkkahjd%2bVqATkQydhLiWmvDE2vI69fzSAePcUrbhDilJLlYewzWWWIak4OepZBwf9gPE35aOABYGa%2bAC11FOQbwSmZT%2bC3UisnO%2f9r55JKlRJkyG5YqLgjW59IxD1wv3plOBUcMl31ZILZ4PQvV%2bBzKAdsQXVIssKzsSxd%2br%2bfQX5mGPxP3UQADdFvkyhryFeNhIYQ7zcGGXe2lfHDz%2foEZWDUi1YuVGE4%2f03Rd1Bd%2fgve2l6Ipsi1teACsx6XMa3NNd%2bNAatGVk8LuX%2bKp%2fDGsWt8Mki6Ai%2bxEVWbcBXSI5dSRDB1Pg8pYIgmYaU37hDITiXhAzK7MqgAEarqmxlTJfhntJUyHamW9MO01t%2fyZjOMGyqLfYu5aY%2fWjseHEG%2fw4CNDocRXWPJenOtC%2f1S%2byxDoJNmktMzfKCBK2QK5vRzAIoRbwZyAbvzeKd3pMKnBHD4pfZZa47ZHDL3fA5ySvJOWDjBr1fMSk6anOOJJ1hDWapPiTn6Fwbq%2bmIOBRIN176e0INxHv0cIAWGSZ6uSYA%2fhel9MXxImvDF%2f3LG8VBQ04QqNaFu3k2CzBnotIYgseNNPR5Xu%2bmzAcj9hPDZLZGIizxBUKDk1oCugJ6OoRm4H3UAR2Qrfuj3tUCSSuSNglMOexjZhiWlI4iqSMh2ZGcYj%2b8Qg0g7aKE4CrTTNwJtl9h1M3hLhD9o5lqDP4lf91tyeGYD7i2pNhCnag6mB7C%2bu14Sg668zWwxpq%2bIchNwz2rWx9VvBn7nC2xm59vInnt2%2fMbtMt1d05wYDs5MkqCtAiLVqvjxXmqLuye4wu17TdOZiTKldGZuMwUfyN9qlHjuO2Worrbke0oKMjRg3Ym4v9xlCj9yX%2fYk2Y7%2bvSlgVRmFo%2bSXUCICb%2bjGi5CYtSTN%2fHxK026N4yE1me0EhlEUjjVqx74LQPxdwG7EmlDP3OGjmmAouWLXDWT3tCR0jFfzt1UI%2fwVTFY48rI3DtFApMdXq%2fs8HacWQqy7qW053EC9ttLknmRSJeG%2fUP%2fS2Lrxa5E2Zp7DVhuszsFb6k%2bs%2bkM3YDZj0DeoUSGbD%2bowtmzZC2wTa36fLG0Db3Fb4n8KbYAEePSgBvRqbNmtgaG2CkgAdu8rrcVoDrW7CD2qncVl4Rc7Ha4vI9rL%2bdR1Pa5Ngum1YfXnF2Z7Jj47avTgFXmmcQR09MOe3vqFe81f9LPMuj1m2CED4CXsYf6EFzfPyrZkrw%2bYkoWuRRvPvTmi8k2M5XC%2bltseg%3d%3d&game_biz=hk4e_global#/log

**Comment by Jelosus2** [comment]
ok, i solved the problem, thank you so much!
